# https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md
# https://github.com/ggml-org/llama.cpp/blob/master/docs/speculative.md
# https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
# ./gemma-4-model-routing.md

[*]
ctx-size = 150000

temp = 1.0
top-p = 0.95
top-k = 64

cache-type-k = q8_0
cache-type-v = q8_0

spec-type = draft-mtp
spec-draft-n-max = 2
draft-p-min = 0.50

spec-draft-type-k = q8_0
spec-draft-type-v = q8_0

# https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF
[unsloth/gemma-4-26B-A4B-Q5_K_XL-NT]
model = /home/saumen/.cache/huggingface/hub/unsloth/gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-UD-Q5_K_XL.gguf
spec-draft-model = /home/saumen/.cache/huggingface/hub/unsloth/gemma-4-26B-A4B-it-GGUF/MTP/gemma-4-26B-A4B-it-MTP-Q8_0.gguf
