# https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md
# https://github.com/ggml-org/llama.cpp/blob/master/docs/speculative.md
# https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md

mmproj =
flash-attn = true
kv-unified = true

cache-type-k = q8_0
cache-type-v = q8_0

cont-batching = true
parallel = 16

########################################

[google/gemma-4-26B-A4B]
# model = /home/saumen/.lmstudio/models/google/gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-Q4_K_M.gguf
model = /home/saumen/.cache/huggingface/hub/unsloth/gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-UD-Q8_K_XL.gguf
alias = gemma-4-26B-A4B
ctx-size = 100000

temp = 1.0
top-p = 0.95
top-k = 64

########################################

[google/gemma-4-31B]
# model = /home/saumen/.lmstudio/models/google/gemma-4-31B-it-GGUF/gemma-4-31B-it-Q4_K_M.gguf
model = /home/saumen/.cache/huggingface/hub/unsloth/gemma-4-31B-it-GGUF/gemma-4-31B-it-UD-Q5_K_XL.gguf
alias = gemma-4-31B
ctx-size = 100000

temp = 1.0
top-p = 0.95
top-k = 64

########################################
