# https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md
# https://github.com/ggml-org/llama.cpp/blob/master/docs/speculative.md
# https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md

################################################################################
# Set model specific settings in the presets.
# Set global settings in the `launcher.sh`
################################################################################

# https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF
# https://unsloth.ai/docs/models/tutorials/glm-4.7-flash
# https://github.com/zai-org/GLM-4.5#inference-with-nvidia-gpus
[unsloth/GLM-4.7-Flash]
model = /home/saumen/.cache/huggingface/hub/unsloth/GLM-4.7-Flash-GGUF/GLM-4.7-Flash-UD-Q5_K_XL.gguf
alias = GLM-4.7-Flash
ctx-size = 200000

n-gpu-layers = 999

temp = 0.7
top-p = 1.0
min-p = 0.01
repeat-penalty = 1.0
