# https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md
# https://github.com/ggml-org/llama.cpp/blob/master/docs/speculative.md
# https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md

mmproj =
flash-attn = true
kv-unified = true

cache-type-k = q8_0
cache-type-v = q8_0

cont-batching = true
parallel = 32

########################################

[unsloth/Qwen3.6-27B-UD-Q5_K_XL-MTP]
model = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-27B-MTP-GGUF/Qwen3.6-27B-UD-Q5_K_XL.gguf
alias = Qwen3.6-27B
ctx-size = 100000

spec-type = draft-mtp
spec-draft-n-max = 2
draft-p-min = 0.50

temp = 0.3
top-p = 0.9
top-k = 20

########################################

[unsloth/qwen3.6-35B-A3B]
model = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q5_K_XL.gguf
alias = Qwen3.6-35B-A3B
ctx-size = 100000

# benchmarks/qwen3.6-35b-a3b/pdf-analysis-benchmarks-02/analysis-report.md
spec-type = draft-mtp
spec-draft-n-max = 2
draft-p-min = 0.50

temp = 0.6
top-p = 0.95

########################################
