# https://huggingface.co/google/gemma-4-31B-it-assistant
# https://github.com/ggml-org/llama.cpp/blob/master/docs/preset.md
# https://github.com/ggml-org/llama.cpp/blob/master/docs/speculative.md
# https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md

[*]
# Claude code defaults to 200k, didn't find a way to override yet.
ctx-size = 70000

# True layers: 48. Structural offset fully covers sparse gating routing steps.
n-gpu-layers = 55

temp = 1.0
top-p = 0.95
top-k = 64

cache-type-k = f16
cache-type-v = f16

spec-type = draft-mtp

draft-p-min = 0.50

[google/gemma-4-26B-A4B-qat]
alias = gemma-4-26B-A4B
model = /home/saumen/.cache/huggingface/hub/google/gemma-4-26B-A4B-it-qat-q4_0-gguf/gemma-4-26B_q4_0-it.gguf
spec-draft-model = /home/saumen/.cache/huggingface/hub/RachidAR/gemma-4-26B-A4B-it-qat-assistant-q4_0-gguf/gemma-4-26b-A4B-it-assistant-Q4_0.gguf
spec-draft-n-max = 2

[google/gemma-4-31B-qat]
alias = gemma-4-31B
model = /home/saumen/.cache/huggingface/hub/google/gemma-4-31B-it-qat-q4_0-gguf/gemma-4-31B_q4_0-it.gguf
spec-draft-model = /home/saumen/.cache/huggingface/hub/RachidAR/gemma-4-31B-it-qat-Q4_0-Q4emb-MTP-assistant-gguf/gemma-4-31b-qat-it-assistant-Q4_0-Q4emb.gguf
spec-draft-n-max = 4
