# Set model specific settings in the presets.
# Set server level settings in the `../launcher-qwen.sh`
########################################################################################################################

[*]
ctx-size = 256000

cache-type-k = f16
cache-type-v = f16

temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
repeat-penalty = 1.0

# Speculation
spec-type = draft-mtp
spec-draft-n-max = 3
draft-p-min = 0.50

########################################################################################################################
# General - Non-thinking
########################################################################################################################

[unsloth/Qwen3.6-35B-A3B-UD-Q6_K-MTP-NT]
model = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q6_K.gguf
mmproj = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F32.gguf
alias = Qwen3.6-35B-A3B-IT, flash

chat-template-kwargs = {"enable_thinking":false}
reasoning = off

temperature = 0.7
top-p = 0.80
presence-penalty = 1.5

########################################################################################################################
# General - Thinking
########################################################################################################################

[unsloth/Qwen3.6-35B-A3B-UD-Q6_K-MTP-General]
model = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q6_K.gguf
mmproj = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F32.gguf
alias = Qwen3.6-35B-A3B-general, general

chat-template-kwargs = {"enable_thinking":true, "preserve_thinking": true }
presence-penalty = 1.5

########################################################################################################################
# Coder
########################################################################################################################

[unsloth/Qwen3.6-35B-A3B-UD-Q6_K-MTP-Coder]
model = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q6_K.gguf
mmproj = /home/saumen/.cache/huggingface/hub/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/mmproj-F32.gguf
alias = Qwen3.6-35B-A3B-Coder, coder

chat-template-kwargs = {"enable_thinking":true, "preserve_thinking": true }
presence-penalty = 0.0

########################################################################################################################
